#!/bin/bash

___generate_setup_script(){
cat << EOF1 | ssh $1 "cat > /home/student/k8s-install.sh"
__MINOR_VER=1.29

_____k8s_initial_setup() {
  # Step 4 - Perform update and upgrade to the system
  apt-get update && apt-get upgrade -y

  # Step 5 - Install required packages
  apt install curl apt-transport-https vim git wget gnupg2 software-properties-common ca-certificates uidmap lsb-release -y

  # Step 6 - Disable swap
  swapoff -a

  # Step 7 - Load br_netfilter, overlay modules to ensure they are available for the subsequent steps
  modprobe overlay
  modprobe br_netfilter

  # Step 8 - Update kernel networking to allow necessary traffic
  cat << EOF | tee /etc/sysctl.d/kubernetes.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

  # Step 9 - Reloads settings from config files without rebooting
  sysctl --system

  # Step 10 - Install the necessary key for the software to install
  mkdir -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  # Step 11 - Install containerd software
  apt-get update && apt-get install containerd.io -y
  containerd config default | tee /etc/containerd/config.toml
  #sed -e "s/SystemdCgroup = false/SystemdCgroup = true/g" -i /etc/containerd/config.toml
sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
  systemctl restart containerd

  # Step 12 - Add repo for Kubernetes
  curl -fsSL https://pkgs.k8s.io/core:/stable:/v\$__MINOR_VER/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v\$__MINOR_VER/deb/ /" >> /etc/apt/sources.list.d/kubernetes.list

  # Step 13 - Install the Kubernetes software, and lock the version
  apt-get update
  apt-get install -y kubeadm kubelet kubectl
  apt-mark hold kubelet kubeadm kubectl
}

#! Check whether k8s is installed or not
if [ ! -d /etc/kubernetes/ ]; then
    if [[ \$(whoami) != "root" ]]; then
        echo "Please run as root"
        exit 1
    else
        _____k8s_initial_setup
    fi
else
    echo "Already installed"
    exit 1
fi

EOF1

echo -e "Generate script in [ $1 ] - /home/student/k8s-install.sh"
}


__TASK_LIST="task1a task1b task1c"
__TASK_HELP="Usage: - lab-help <task1a | task1b | task1c>"
if [[ $# -eq 0 ]] ; then
      echo "$__TASK_HELP"
      exit 1
elif [[ "$__TASK_LIST" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
      if [[ $1 == "task1a" ]]; then
        ___generate_setup_script k8s-cp
      elif [[ $1 == "task1b" ]]; then
        ___generate_setup_script k8s-worker-1
      elif [[ $1 == "task1c" ]]; then
        ___generate_setup_script k8s-worker-2
      else
        echo "$__TASK_HELP"
        exit 1
      fi 
else
    echo "$__TASK_HELP"
    exit 1
fi
