#!/bin/bash

___lab_task3(){
  cat << EOF > $1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: web-one
            port:
              number: 80

EOF
  echo -e "Generate $1"
}
__TASK_LIST="task3"
__TASK_HELP="Usage: - lab9-help <task3>"
if [[ $# -eq 0 ]] ; then
      echo "$__TASK_HELP"
      exit 1
elif [[ "$__TASK_LIST" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
      if [[ $1 == "task2" ]]; then
        ___lab_task2 /home/student/ingress_rules.yaml
      else
        echo "$__TASK_HELP"
        exit 1
      fi 
else
    echo "$__TASK_HELP"
    exit 1
fi
