#!/bin/bash

___lab9_task4(){
  cat << EOF > $1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-test-app-svc
            port:
              number: 80
        path: /
        pathType: Prefix

EOF
  echo -e "Generate $1"
}
__TASK_LIST="task4"
__TASK_HELP="Usage: - lab9-help <task4>"
if [[ $# -eq 0 ]] ; then
      echo "$__TASK_HELP"
      exit 1
elif [[ "$__TASK_LIST" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
      if [[ $1 == "task4" ]]; then
        ___lab9_task4 /home/student/ingress_rules.yaml
      else
        echo "$__TASK_HELP"
        exit 1
      fi 
else
    echo "$__TASK_HELP"
    exit 1
fi
