apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-demo
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  storagePolicyName: my_k8s_sp